package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("leroy test again")
    void generatedTest() {
        step("open 'https://www.leroymerlin.gr/gr'", () -> {
            step("// todo: just add selenium action");
        });

        step("do smthing", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.leroymerlin.gr/gr'", () ->
            open("https://www.leroymerlin.gr/gr"));

        step("Page title should have text 'Leroy Merlin: Τα πάντα για την ανακαίνιση του σπιτιού σου, σε έναν προορισμό!'", () -> {
            String expectedTitle = "Leroy Merlin: Τα πάντα για την ανακαίνιση του σπιτιού σου, σε έναν προορισμό!";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.leroymerlin.gr/gr'", () ->
            open("https://www.leroymerlin.gr/gr"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}